// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXLFe0D4YMuKNt01qysaXV4SNDJBW2qA',
    appId: '1:177395710789:web:ff8c36b08ff39952861c2c',
    messagingSenderId: '177395710789',
    projectId: 'whatsap-flutter-backend',
    authDomain: 'whatsap-flutter-backend.firebaseapp.com',
    storageBucket: 'whatsap-flutter-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGKyj4Mah3mFkghfjy-KzXm6M-4yYnTA',
    appId: '1:177395710789:android:43b68607cdeae71a861c2c',
    messagingSenderId: '177395710789',
    projectId: 'whatsap-flutter-backend',
    storageBucket: 'whatsap-flutter-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngHbSH0chlTQYZUsLW4QwU_v0WuXsnmM',
    appId: '1:177395710789:ios:5b67f1a89324abb8861c2c',
    messagingSenderId: '177395710789',
    projectId: 'whatsap-flutter-backend',
    storageBucket: 'whatsap-flutter-backend.appspot.com',
    iosClientId: '177395710789-1stducq15cj7o58p3h9c4cm4r1h3fcf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAngHbSH0chlTQYZUsLW4QwU_v0WuXsnmM',
    appId: '1:177395710789:ios:5b67f1a89324abb8861c2c',
    messagingSenderId: '177395710789',
    projectId: 'whatsap-flutter-backend',
    storageBucket: 'whatsap-flutter-backend.appspot.com',
    iosClientId: '177395710789-1stducq15cj7o58p3h9c4cm4r1h3fcf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter',
  );
}
